In [1]:
#Importação das bibliotecas que serão usadas
import os
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Anexo_Arquivo_Dados_Projeto_Logica_e_programacao_de_computadores.csv')
df

,data,precip,maxima,minima,horas_insol,temp_media,um_relativa,vel_vento
0,01/01/1961,8.6,39.5,13.4,4.3,18.2,75.8,2.6
1,02/01/1961,2.4,25.0,19.9,11.9,14.7,79.1,1.6
2,03/01/1961,10.1,23.3,14.5,9.8,24.0,78.8,2.0
3,04/01/1961,18.6,22.1,15.8,7.3,17.7,83.7,1.6
4,05/01/1961,1.5,27.3,15.3,4.5,16.0,66.2,1.2
...,...,...,...,...,...,...,...,...
20265,26/06/2016,7.1,25.3,18.2,5.7,23.9,59.9,0.0
20266,27/06/2016,0.0,25.3,24.6,11.1,23.3,54.8,3.3
20267,28/06/2016,0.0,21.7,19.0,7.9,11.2,75.2,2.2
20268,29/06/2016,0.0,21.1,12.8,11.8,24.5,91.4,0.0
20269,30/06/2016,1.3,23.4,12.6,10.3,20.9,81.7,2.1

In [3]:
#Verificando se existe valores nulos:
df.isnull().sum()

data           0
precip         0
maxima         0
minima         0
horas_insol    0
temp_media     0
um_relativa    0
vel_vento      0
dtype: int64

In [4]:
#Verificando se existem valores duplicados:
df.duplicated().any()

np.False_

a) Visualização de intervalo de dados em modo texto: a partir de entradas do usuário, sua implementação deve permitir a visualização dos dados que foram carregados do arquivo. O usuário deve informar o período que quer ver, ou seja, deve indicar o mês e ano iniciais, bem como o mês e ano finais que deseja visualizar os dados. Permita também que o usuário informe se quer ver 1) todos os dados, 2) apenas os de precipitação, 3) apenas os de temperatura, ou 4) apenas os de umidade e vento para o período informado.

In [ ]:
#Implementar com funções.

def opcao_invalida():
    print('Opção inválida! Aperte qualquer tecla para voltar ao início.')
    main()


def escolha(): #provavelmente ce vai ter que fazer de uma forma diferente, vê de noite.
    while True:
        try:
            mesinicial = int(input('Informe o valor do mês inicial para visualizar (1 a 12):'))
            if 1 <= mesinicial <= 12:
                return mesinicial
            else:
                opcao_invalida()
        except ValueError:
            opcao_invalida()
        break

    while True:
        try:
            mesfinal = int(input('informe o valor do mês final para visualizar (1 a 12):'))
            if 1 <= mesfinal <= 12:
                return mesfinal
            else:
                opcao_invalida()
        except ValueError:
            opcao_invalida()
        break

    while True:
        try:
            anoinicial = int(input('Informe o valor do ano inicial para visualizar (1961 a 2016):'))
            if 1961 <= anoinicial <= 2016:
                return anoinicial
            else:
                opcao_invalida()
        except ValueError:
            opcao_invalida()
        break

    while True:
        try:
            anofinal = int(input('informe o valor do ano final para visualizar (1961 a 2016):'))
            if 1961 <= anofinal <= 2016:
                return anofinal
            else:
                opcao_invalida()
        except ValueError:
            opcao_invalida()
        break

mesinicial = escolha()
mesfinal = escolha()
anoinicial = escolha()
anofinal  = escolha()

print(mesinicial)
print(mesfinal)
print(anoinicial)
print(anofinal)
def main():
    os.system('cls')
    escolha()

if __name__ =='__main__ ':
    main()

1
2
1
2